name: Jekyll Site CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Tar site
      run: |
        mkdir ../jekyll
        cp -TR  . ../jekyll
        tar -cvf deploy.tar ../jekyll/
    
    - name: Copy result to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "deploy.tar"
        target: "/var/www/html"
    
    - name: Extract site files and build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /var/www/html
          rm -rf $(ls -I deploy.tar)
          tar xf deploy.tar && rm deploy.tar
          mv jekyll/* . && rm -rf jekyll/
          bundle install --path ~/.gem
          JEKYLL_ENV=production bundle exec jekyll build
          rm * && mv _site/* . && rm -rf _site/
